version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: foo_database
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"